### ISSUE TITLE
exam like client environment

### ISSUE THREAD

**Issue by walidshaari** [k4mrul/kubernetes#1]
#  Great job,  Here are my comments:
- Not sure if in the exam you will have access to nerdctl, most likely crictl and crt
- Exam network is flannel or calico or loopback
-  no one installs LXC by default, it will be only Linux, vagrant would work on Windows and Mac

**Comment by k4mrul** [comment]
Thanks for your input @walidshaari 

I just switched container runtime from containerd to docker. So no more crt.
I agree with your other points.

**Comment by walidshaari** [comment]
but exam environment most likely is not docker
